cache:
  CACHE_TYPE: simple
jwt:
  SECRET: foo
  EXPIRE_HOURS: 24
app:
  SALT: bar
  ENV: dev
  SECRET: ^753*&FdFS#4D
  HOST: 127.0.0.1
  PORT: 8000
db:
  MYSQL: mysql+pymysql://root:2020013061@mysql:3306/thss